import os

Import('*')

e = env.Clone()

#
# tbonaonic.bit should be a soft link to the actual, versioned
# FPGA config file, to save having to edit this file and others
# every day during the development cycle. Once we near production
# consider changing this to reference a versioned filename.
#
fpga = ['tbonaonic.bit']

for img in fpga :
    target = os.path.join(conf['fpga_blddir'], img)
    f = e.Command(target, img, "cp -f $SOURCE $TARGET" )
    utils.install(e,f)

compvalue = [
             'compvalues/compvalues.positive',
             'compvalues/compvalues.zero'
            ]
if conf.has_key('app_type'):
    # copy the aonic compvalues only if the target is not ccpu_changeling. the changeling
    # build uses the compvalues from the thunderbird directory
    if conf['app_type'] != 'ccpu_changeling':
        for file in compvalue :
            target = os.path.join(conf['fpga_blddir'], file)
            f = e.Command(target, file, "cp -f $SOURCE $TARGET")
            utils.install(e, f)

aonic_compvalue = [
             'compvalues/compvalues_aonic.positive',
             'compvalues/compvalues_aonic.zero'
            ]
for file in aonic_compvalue :
    target = os.path.join(conf['fpga_blddir'], file)
    f = e.Command(target, file, "cp -f $SOURCE $TARGET")
    utils.install(e, f)

# Local Variables:
# mode:python
# End:
# vim: syntax=python

